/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ninewanwan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static java.time.Clock.system;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joyl1022
 */
public class gunung extends javax.swing.JFrame {

    /**
     * Creates new form DemoDatabase
     */
    public gunung() {
        initComponents();
    }
    
    private static Connection c;
    private static Statement s;
    private static ResultSet rs;
    
    
    
    private static DefaultTableModel model = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jtp = new javax.swing.JTabbedPane();
        addDataTab = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        baturadenButton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        Notelp2Field = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        NikField = new javax.swing.JTextField();
        kaliwadasButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        AlamatField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        NotelpField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bambanganButton = new javax.swing.JRadioButton();
        BulanBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jumlahrombonganSpinner = new javax.swing.JSpinner();
        tanggalSpinner = new javax.swing.JSpinner();
        tahunSpinner = new javax.swing.JSpinner();
        nextButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        seeDataTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        NamaAField = new javax.swing.JTextField();
        NikAField = new javax.swing.JTextField();
        SubmitAButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        jLabel20 = new javax.swing.JLabel();
        cetakButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nim = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Notelp = new javax.swing.JLabel();
        NoTelp2 = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        JumlahAnggota = new javax.swing.JLabel();
        NamaLabel = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        notelponLabel = new javax.swing.JLabel();
        notelpon2Label = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        jumlahrombonganLabel = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        TanggalLabel = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jalurLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addDataTab.setBackground(new java.awt.Color(150, 150, 252));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Selamat Datang di Aplikasi Booking Online Gunung Selamet");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Silahkan Pilih Jalur Pendakian");

        buttonGroup1.add(baturadenButton);
        baturadenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baturadenButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("No.Telepon");

        NikField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NikFieldActionPerformed(evt);
            }
        });

        buttonGroup1.add(kaliwadasButton);
        kaliwadasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliwadasButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pilih Tanggal Booking");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("NIK Ketua Rombongan");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Via Baturaden");

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Via Kaliwadas");

        AlamatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlamatFieldActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Jumlah Rombongan");

        NotelpField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotelpFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("No.Telepon Darurat");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Alamat");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Email");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nama Ketua Rombongan");

        buttonGroup1.add(bambanganButton);
        bambanganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bambanganButtonActionPerformed(evt);
            }
        });

        BulanBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BulanBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        BulanBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulanBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Via Bambangan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(NotelpField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(Notelp2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EmailField)
                                            .addComponent(jLabel12)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tanggalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(BulanBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tahunSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel18)
                                            .addComponent(jumlahrombonganSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NameField))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(NikField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(AlamatField))
                                .addGap(35, 35, 35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(153, 153, 153)
                                .addComponent(jLabel5)
                                .addGap(121, 121, 121))))
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(bambanganButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kaliwadasButton)
                        .addGap(224, 224, 224)
                        .addComponent(baturadenButton)
                        .addGap(150, 150, 150))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bambanganButton)
                        .addComponent(baturadenButton))
                    .addComponent(kaliwadasButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BulanBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NikField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NotelpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Notelp2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlamatField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahrombonganSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDataTabLayout = new javax.swing.GroupLayout(addDataTab);
        addDataTab.setLayout(addDataTabLayout);
        addDataTabLayout.setHorizontalGroup(
            addDataTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDataTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(addDataTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
            .addGroup(addDataTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addDataTabLayout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(183, Short.MAX_VALUE)))
        );
        addDataTabLayout.setVerticalGroup(
            addDataTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDataTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addDataTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(submitButton)
                    .addComponent(nextButton)
                    .addComponent(editButton))
                .addGap(92, 92, 92))
            .addGroup(addDataTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addDataTabLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(661, Short.MAX_VALUE)))
        );

        jtp.addTab("Add Data", addDataTab);

        dataTable.setModel(model);
        setupTable();
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);

        deleteButton.setText("Delete Data");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seeDataTabLayout = new javax.swing.GroupLayout(seeDataTab);
        seeDataTab.setLayout(seeDataTabLayout);
        seeDataTabLayout.setHorizontalGroup(
            seeDataTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seeDataTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addGap(44, 44, 44))
            .addGroup(seeDataTabLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seeDataTabLayout.setVerticalGroup(
            seeDataTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seeDataTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jtp.addTab("See Data", seeDataTab);

        jPanel3.setBackground(new java.awt.Color(68, 127, 209));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Nama  : ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Nik      :");

        NamaAField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaAFieldActionPerformed(evt);
            }
        });

        SubmitAButton.setText("Submit");
        SubmitAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitAButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(List);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("Silahkan Isi Data Dari Anggota Anda");

        cetakButton.setText("Cetak");
        cetakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(SubmitAButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NikAField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(18, 18, 18)
                                    .addComponent(NamaAField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(cetakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(NamaAField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NikAField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(SubmitAButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cetakButton)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        jtp.addTab("Data Anggota", jPanel3);

        jPanel2.setBackground(new java.awt.Color(79, 106, 172));
        jPanel2.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Ketua              : ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        nim.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nim.setForeground(new java.awt.Color(255, 255, 255));
        nim.setText("Nim Ketua                 : ");
        jPanel2.add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email                          : ");
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        Notelp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Notelp.setForeground(new java.awt.Color(255, 255, 255));
        Notelp.setText("No Telepon               : ");
        jPanel2.add(Notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        NoTelp2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NoTelp2.setForeground(new java.awt.Color(255, 255, 255));
        NoTelp2.setText("No Telepon Darurat : ");
        jPanel2.add(NoTelp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        Alamat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Alamat.setForeground(new java.awt.Color(255, 255, 255));
        Alamat.setText("Alamat                       : ");
        jPanel2.add(Alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        JumlahAnggota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JumlahAnggota.setForeground(new java.awt.Color(255, 255, 255));
        JumlahAnggota.setText("Jumlah Anggota      : ");
        jPanel2.add(JumlahAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        NamaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NamaLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(NamaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 407, 20));

        nimLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nimLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(nimLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 407, 17));

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 420, 17));

        notelponLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        notelponLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(notelponLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 407, 17));

        notelpon2Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        notelpon2Label.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(notelpon2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 407, 17));

        alamatLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alamatLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(alamatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 410, 20));

        jumlahrombonganLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jumlahrombonganLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jumlahrombonganLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 407, 17));

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel2.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tanggal Boking        : ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        TanggalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TanggalLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(TanggalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 407, 17));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Jalur Pendakian        : ");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jalurLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jalurLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jalurLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 400, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("E-Tiket");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 120, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ninewanwan/ini.jpeg"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 830, 410));

        jtp.addTab("Cetak", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jtp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

                String Nik = NikField.getText();
                String nama = NameField.getText();
                String notelp = NotelpField.getText();
                String notelp2 = Notelp2Field.getText();
                String email = EmailField.getText();
                String alamat = AlamatField.getText();
                String bulan = (String)BulanBox.getSelectedItem();
                int jumlah_rombongan = (int)jumlahrombonganSpinner.getValue();
                int tanggal = (int)tanggalSpinner.getValue();
                int tahun = (int)tahunSpinner.getValue();
                

                boolean emptyFields = (Nik.equals("") || nama.equals("") || email.equals("") || alamat.equals("") );
                if(emptyFields) {
                    JOptionPane.showMessageDialog(null, "Tolong Isikan Data Terlabih Dahulu");

                }else {
                    try {
                        openDb();
                        s.executeUpdate(
                                "INSERT INTO tabel VALUE ('" + Nik + "','" + nama + "','" + notelp + "','" + notelp2 + "', '" + email + "', '" + alamat + "','" + jumlah_rombongan + "')"
                        );

                        Object[] row = {Nik, nama, notelp, notelp2, email, alamat, jumlah_rombongan};
                        model.addRow(row);

                        JOptionPane.showMessageDialog(null, "Data added!");
                

                    }catch(SQLException | ClassNotFoundException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());

                    }finally {
                        closeDb();
                    
                    }
                     jtp.setSelectedIndex(1);
                }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        NameField.setText("");
        NikField.setText("");
        NotelpField.setText("");
        Notelp2Field.setText("");
        EmailField.setText("");
        AlamatField.setText("");
        jumlahrombonganSpinner.setValue(0);
        tanggalSpinner.setValue(0);
        tahunSpinner.setValue(0);
        
        JOptionPane.showMessageDialog(null, "Form Cleared!");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
          try {
                        openDb();
                        s.executeUpdate(
                                "DELETE From tabel");
                        int row = dataTable.getRowCount();
                        
                        for (int a=0; a<row; a++){
                            model.removeRow(0);
                        }
                        JOptionPane.showMessageDialog(null, "Data cleared!");
                    }catch(SQLException | ClassNotFoundException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
                        
                    }finally {
                        closeDb();
                    }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void BulanBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BulanBoxActionPerformed

    private void NotelpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotelpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotelpFieldActionPerformed

    private void AlamatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlamatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlamatFieldActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void kaliwadasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliwadasButtonActionPerformed
        String kl="Kaliwadas";
        
        bambanganButton.setSelected(false);
        baturadenButton.setSelected(false);
        
        jalurLabel.setText(kl);
    }//GEN-LAST:event_kaliwadasButtonActionPerformed

    private void NikFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NikFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NikFieldActionPerformed

    private void bambanganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bambanganButtonActionPerformed
       String bm = "Bambangan";
       
       kaliwadasButton.setSelected(false);
       baturadenButton.setSelected(false);
       
       jalurLabel.setText(bm);
    }//GEN-LAST:event_bambanganButtonActionPerformed

    private void baturadenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baturadenButtonActionPerformed
        String bt = "Baturaden";
        
        kaliwadasButton.setSelected(false);
        bambanganButton.setSelected(false);
        
        jalurLabel.setText(bt);
    }//GEN-LAST:event_baturadenButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        jtp.setSelectedIndex(2);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
       jtp.setSelectedIndex(0);
          try {
               int i = dataTable.getSelectedRow();
             if(i<-1){
               NikField.setText(model.getValueAt(i, 0).toString());
               NameField.setText(model.getValueAt(i, 1).toString());
               NotelpField.setText(model.getValueAt(i, 2).toString());
               Notelp2Field.setText(model.getValueAt(i, 3).toString());
               EmailField.setText(model.getValueAt(i, 4).toString());
               AlamatField.setText(model.getValueAt(i, 5).toString());
             }
                        openDb();
                         rs = s.executeQuery("SELECT * FROM tabel WHERE nik");
                        
                         if (rs.next()){
                            NikField.setText(rs.getNString("Nik"));
                            NameField.setText(rs.getNString("nama"));
                            NotelpField.setText(rs.getNString("notelp"));
                            Notelp2Field.setText(rs.getNString("notelp2"));
                            EmailField.setText(rs.getNString("email"));
                            AlamatField.setText(rs.getNString("alamat")); 
                         } 
                    }catch(SQLException | ClassNotFoundException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
                        
                    }finally {
                        closeDb();
                    }
    }//GEN-LAST:event_dataTableMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
       try {
            openDb();
                        s.executeUpdate(
                                "UPDATE tabel set nama='" + NameField.getText() + "',notelp='" + NotelpField.getText() + "',notelp2='" + Notelp2Field.getText() + "',email='" + EmailField.getText() + "',alamat='" + AlamatField.getText() + "' where Nik = '"+NikField.getText()+"'"
                        );
                        
                        rs = s.executeQuery("SELECT * FROM tabel WHERE nik");
                        liat();

                        JOptionPane.showMessageDialog(null, "Data added!");
                        

                    }catch(SQLException | ClassNotFoundException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());

                    }finally {
                        closeDb();
                    
                    }
                     jtp.setSelectedIndex(1);
    }//GEN-LAST:event_editButtonActionPerformed

    private void NamaAFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaAFieldActionPerformed
        // TODO add y
    }//GEN-LAST:event_NamaAFieldActionPerformed

    private void SubmitAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitAButtonActionPerformed
    String Na = NamaAField.getText();
    mdl.addElement(Na);
    int Ni = Integer.parseInt(NikAField.getText());
    mdl.addElement(Ni);
    List.setModel(mdl);
    }//GEN-LAST:event_SubmitAButtonActionPerformed

    private void cetakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakButtonActionPerformed
      String Nik = NikField.getText();
        String nama = NameField.getText();
        String notelp = NotelpField.getText();
        String notelp2 = Notelp2Field.getText();
        String email = EmailField.getText();
        String alamat = AlamatField.getText();
        String bulan = (String)BulanBox.getSelectedItem();
        int jumlah_rombongan = (int)jumlahrombonganSpinner.getValue();
        int tanggal = (int)tanggalSpinner.getValue();
        int tahun = (int)tahunSpinner.getValue();
        
        NamaLabel.setText(nama);
        nimLabel.setText(Nik);
        emailLabel.setText(email);
        notelponLabel.setText(notelp);
        notelpon2Label.setText(notelp2);
        alamatLabel.setText(alamat);
        jumlahrombonganLabel.setText(String.valueOf(jumlah_rombongan));
        TanggalLabel.setText(String.valueOf(tanggal)+" "+bulan+" "+String.valueOf(tahun));

        jtp.setSelectedIndex(3);
    }//GEN-LAST:event_cetakButtonActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        home a = new home();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private static void openDb() throws ClassNotFoundException, SQLException {
        String URL = "jdbc:mysql://localhost:3306/booking";
        String USERNAME = "root";
        String PASSWORD = "";

        Class.forName("com.mysql.cj.jdbc.Driver");
         c = DriverManager.getConnection(URL, USERNAME, PASSWORD);
         s = c.createStatement();
    }


    private static void closeDb() {
        try {
            rs.close();
            s.close();
            c.close();
        }catch(SQLException e) {
            e.printStackTrace();
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gunung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gunung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gunung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gunung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gunung().setVisible(true);
            }
        });
    }

    private static void setupTable() {
        model.addColumn("Nik");
        model.addColumn("Nama");
        model.addColumn("NoTelpon");
        model.addColumn("NoTelpon Darurat");
        model.addColumn("Email");
        model.addColumn("Alamat");
        model.addColumn("Jumlah Rombongan");
        

        try {
            openDb();
            rs = s.executeQuery("SELECT * FROM tabel");

            while(rs.next()) {
                Object[] row = {
                    rs.getString("Nik"),
                    rs.getString("nama"),
                    rs.getString("notelp"),
                    rs.getString("notelp2"),
                    rs.getString("email"),
                    rs.getString("alamat"),
                    rs.getInt("jumlah_rombongan")
                };
                model.addRow(row);
            }

        }catch(SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();

        }finally {
            closeDb();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JTextField AlamatField;
    private javax.swing.JComboBox<String> BulanBox;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel JumlahAnggota;
    private javax.swing.JList<String> List;
    private javax.swing.JTextField NamaAField;
    private javax.swing.JLabel NamaLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField NikAField;
    private javax.swing.JTextField NikField;
    private javax.swing.JLabel NoTelp2;
    private javax.swing.JLabel Notelp;
    private javax.swing.JTextField Notelp2Field;
    private javax.swing.JTextField NotelpField;
    private javax.swing.JButton SubmitAButton;
    private javax.swing.JLabel TanggalLabel;
    private javax.swing.JPanel addDataTab;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JRadioButton bambanganButton;
    private javax.swing.JRadioButton baturadenButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cetakButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jalurLabel;
    private javax.swing.JTabbedPane jtp;
    private javax.swing.JLabel jumlahrombonganLabel;
    private javax.swing.JSpinner jumlahrombonganSpinner;
    private javax.swing.JRadioButton kaliwadasButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel nim;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JLabel notelpon2Label;
    private javax.swing.JLabel notelponLabel;
    private javax.swing.JPanel seeDataTab;
    private javax.swing.JButton submitButton;
    private javax.swing.JSpinner tahunSpinner;
    private javax.swing.JSpinner tanggalSpinner;
    // End of variables declaration//GEN-END:variables

    private void liat() {
        int row = dataTable.getRowCount();
        for (int i=0; i<row; i++){
            model.removeRow(0);
        }
      try {
                        openDb();
                         rs = s.executeQuery("SELECT * FROM tabel WHERE nik");
                        
                    while(rs.next()) {
                    String Object[] = {
                    rs.getString("Nik"),
                    rs.getString("nama"),
                    rs.getString("notelp"),
                    rs.getString("notelp2"),
                    rs.getString("email"),
                    rs.getString("alamat")
                    
                }; 
                model.addRow(Object);      
            }
                    }catch(SQLException | ClassNotFoundException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, ex.getLocalizedMessage());
                        
                    }finally {
                        closeDb();
                    }
    }
  DefaultListModel mdl = new DefaultListModel();
}

    
    // private DefaultTableModel model;
